#!/bin/sh
echo task $1 $2 seq:$PARALLEL_SEQ host:$(hostname) date:$(date)
python main.py --random TRUE --seed $1 --Z $2 --stellar_tides TRUE --max_time 15000.0 --method RK45 --nsflag 3 --lamb 0.1 --alpha 0.2